
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>

    <meta content="noindex" name="robots"/>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title>UOIT Expert Centre | UOIT - ExpertFile</title>
    <meta content="UOIT Expert Centre" name="description"/>
    <meta content="expert, centre, experts, expertfile" name="keywords"/>

    <!-- UOIT STYLES -->
    <link href="https://uoit.ca/favicon.ico" rel="icon" type="image/x-icon"/>
    <link href="https://shared.uoit.ca/global/files/css/global.css" rel="stylesheet"/>
    <!--[if lte IE 9]>
    <link href="https://shared.uoit.ca/global/files/css/globalie.css" media="all" rel="stylesheet"/>
    <![endif]-->
    <link href="https://uoit.ca/sandbox/base/files/css/app.css" rel="stylesheet"/>
    <!-- FONT AWESOME 4.4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CUSTOM STYLES / COMPONENTS -->
    <link href="css/flickity.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="css/components.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="css/styles.css" media="all" rel="stylesheet" type="text/css"/>
        
    <script src="https://shared.uoit.ca/global/files/js/modernizr.min.js" type="text/javascript"></script>
    <script src="https://shared.uoit.ca/global/bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>

</head>
<body class="nav-on-left">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-12659975-35', 'auto');
      ga('send', 'pageview');

    </script>

    <a href="#main_content" id="btn_skip_to_content" tabindex="1">Skip to main content</a> 
    
    <header class="cd-main-header">
        <section class="topWrapper_nav">
            <div class="emergencyInfo">
                <div>
                    <a href="http://uoit.ca/emergency" onclick="ga('send','event','button','click','topNav_emergencyInfo');">Emergency information</a>
                </div>
            </div>

            <nav class="top_nav" role="navigation">
                <div class="row">
                    <div class="top_links">
                        <ul>
                            <li><div class="nav_col_title"><span>Quick</span> <span>links</span></div></li>
                            <li>
                                <ul>
                                    <li><a href="http://refresh.uoit.ca/main/current-students/academics-and-programs/academic-calendars/index.php">Academic Calendar</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </section>

        <section class="topWrapper_search">
          <section class="top_search">
            <div class="row">
              <div class="search_person">
                <a class="button" href="/directory" id="btn_search_person" onclick="ga('send','event','button','click','topNav_findAPerson');"><span>Find a person</span></a>
              </div>
              <form action="https://uoit.ca/search-results.php" id="main-search" method="get">
                <input id="txt_search" name="q" placeholder="Search UOIT" title="Search UOIT" type="text"/>
                <input class="button" id="btn_search" onclick="ga('send','event','button','click','topNav_searchSubmit');" type="submit" value="Search"/>
                <input name="site" type="hidden" value="uoit"/>
                <input name="client" type="hidden" value="uoit"/>
                <input name="proxystylesheet" type="hidden" value="uoit"/>
                <input name="output" type="hidden" value="xml_no_dtd"/>
              </form>   
            </div>
          </section>
        </section>

        <div class="toggle_top_nav">  
          <button class="btn_toggleTopSection" id="btn_toggleTopNav" onclick="ga('send','event','button','click','topNav_quickLinks');"><span>Quick links</span></button>
          <button class="btn_toggleTopSection" id="btn_toggleSearch" onclick="ga('send','event','button','click','topNav_search');"><span>Search</span></button>
        </div>

        <div class="nav_row">
            <div class="row">
                <div class="logoTitle">
                    <h1><a href="http://uoit.ca" title="UOIT home page"><img alt="University of Ontario Institute of Technology logo" src="https://shared.uoit.ca/global/files/img/logos/UOIT_RGB.png"/></a></h1>
                </div>
            </div>
            
            <div class="cd-header-buttons">
                <button class="cd-nav-trigger">Menu</button>
            </div>
        </div>
    </header>
    
    <!-- Main content -->
    <section class="cd-main-content" id="main_content">
        <nav aria-label="Breadcrumbs" class="breadcrumbs" role="menubar">
            <li role="menuitem"><a href="../index.php">UOIT</a></li>
        </nav> 


        <div class="grid"> 
                    

            <div class="content_old_browser">
                <br/><br/>
                <div class="Message">
                    <content/>
                </div>
            </div> 

            
            <!-- MAIN CONTENT STARTS HERE -->